
simulation:
  minimalCharacteristicLength: 0.0001
  simulationType: COLLISION
  inputSource: ["../example-config/CTwrtMinCL/data.yaml"]  # Use the custom satellite configuration with high relative velocity
  enforceMassConservation: True

inputOutput:
  target: ["../results_analysis/CTwrtMinCL/input/input.csv", "../results_analysis/CTwrtMinCL/input/input.vtu"]
  kepler: False

resultOutput:
  target: ["../results_analysis/CTwrtMinCL/output/output.csv", "../results_analysis/CTwrtMinCL/output/output.vtu"]
  kepler: False