
simulation:
  minimalCharacteristicLength: 0.01
  simulationType: COLLISION
  enforceMassConservation: True
  inputSource: ["../example-config/min-projectile-mass/data_0.0032.yaml"]  # Use the custom satellite configuration with high relative velocity

inputOutput:
  target: ["../results_analysis/min-projectile-mass/input/0.0032_input.csv", "../results_analysis/min-projectile-mass/input/0.0032_input.vtu"]
  kepler: False

resultOutput:
  target: ["../results_analysis/min-projectile-mass/output/0.0032_result.csv", "../results_analysis/min-projectile-mass/output/0.0032_result.vtu"]
  kepler: False