
simulation:
  minimalCharacteristicLength: 0.05
  simulationType: COLLISION
  inputSource: ["../example-config/catastrophic-vs-noncatastrophic/data_cat_low_velocity.yaml"]  # Use the custom satellite configuration with low relative velocity

inputOutput:
  target: ["../results_analysis/catastrophic_vs_noncatastrophic/input/cat_low_velocity_input.csv", "../results_analysis/catastrophic_vs_noncatastrophic/input/cat_low_velocity_input.vtu"]
  kepler: False

resultOutput:
  target: ["../results_analysis/catastrophic_vs_noncatastrophic/output/cat_low_velocity_result.csv", "../results_analysis/catastrophic_vs_noncatastrophic/output/cat_low_velocity_result.vtu"]
  kepler: False